import Image from 'next/image'
import {Container, MainContainer} from '../styles/pages/index'
import Head from 'next/head'

import Logo from '../assets/logo.svg'
import Link from 'next/link'

export default function Home() {
  return (
    <MainContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div>
          <h1>
            Share your ideas trought daily posts
          </h1>
          <h3>
            Post about your projects and doubts, find developer from all over the world.
          </h3>
        </div>
        <div className='logo'>
          <Image height={200} width={280} alt="Logo do blog" src={Logo}/>
        </div>
      </Container>

      <Container>
        <div>
          <h1>New user?</h1>
          <h3>Click here to sign up.</h3>
          <Link href="/signUp">
            <button>go</button>
          </Link>
        </div>
        <div>
          <h1>Not a new user?</h1>
          <h3>Sign in now.</h3>
          <Link href="/signIn">
            <button>sign in</button>
          </Link>
        </div>
      </Container>
      
      
    </MainContainer>
  )
}
